spring.application.name=jwt_and_refresh_token_authentication
spring.datasource.url=jdbc:postgresql://localhost:5432/bootcamp
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=9095

# JWT Configuration
jwt.secret=super_ultra_secret_key_for_jwt_token
# 1 saat
jwt.expiration=3600000

# Refresh configuration
jwt.refresh.expiration=1209600000

